### ISSUE TITLE
[FEAT]: Disable Role API

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#157]
## Description:
Implement an endpoint to disable roles. This endpoint will allow admins to disable roles that are no longer required within an organization.
***

## Acceptance Criteria:
**Endpoint**:

-   It should be a properly `PROTECTED` endpoint, requiring user authentication with access token
-   It should be a `PUT` request at `/api/v1/organizations/:{organizationId}/roles/:{roleId}/disable`.
-   Ensures that the IDs of the organization and role are passed as parameters, and that both exist in the database
-   Ensures that every request is from an admin or super admin of the organization, who is authorized to disable roles
-   Ensures that all the users on the disabled `Role` are moved to the organization's default role for successful requests

**Database Update**:

- Update the database to reflect that the `Role` is disabled (i.e: is no longer active).
- Update database to move all the users on the disabled role to the default role.

**Success and Error Handling**:

- Handle success and error responses appropriately.

**Testing and Debugging**:

- Write unit tests for the role deactivation endpoint.
- Perform integration testing to ensure the endpoint works as expected.
- Debug any issues that arise during testing.
***

## Purpose
To provide an endpoint for admins to disable any role within their organization, ensuring that only authorized users can perform this action, and maintaining system security.
***

## Requirements

- [ ] Develop server-side logic to disable a Role within the organization.
- [ ] Properly update the database to reflect all changes, on Role and User tables.
- [ ] Ensure compliance with internal standards for handling role related updates.
***

## Expected Outcome:
Authorised admins should be able to disable roles as long as they meet required criteria
***

## Tasks:
 

- [ ] Create endpoint (`PUT: /api/v1/organisations/:{organizationId}/roles/:{roleId}/disable`) to handle valid request.
- [ ]  Validate organizationId and roleId provided on the server side, and access `Role`
- [ ]  Update database to reflect disabled (`is_active=False`) for Role.
- [ ]  Update database to move users on the disabled role to the organization's default role, which has the basic permissions required for a user to be a member of an organization
- [ ]  Implement server-side logic to handle successful and failed role disabling requests.
- [ ]  Ensure all sensitive data is encrypted and secure.
- [ ]  Implement logging for successful and failed requests.
- [ ]  Write unit tests and integration tests for the endpoint.

**Example Request [With Auth Token]:**
```
curl -X PUT {rootdomain}/api/v1/organisations/:{organizationId}/roles/:{roleId}/disable \
     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
     -d ....
```

**Response Body [Success]:**
`{ "status_code": 200, "message": "Role disabled successfully." }`

**Response Body [Errors]:**

- _Unrecognized user:_ `{ "status_code": 401, "message": "Could not validate credentials." }`
- _Invalid admin:_ `{ "status_code": 403, "message": "Insufficient permission." }`
- _Invalid organization or role ID:_ `{ "status_code": 404, "message": "Organization or role not found." }`
- _Failed disabling:_ `{ "status_code": 400, "message": "Unable to disable role." }`

***

## Testing:

- [ ]  Write end-to-end backend unit tests for the full disabling process.
- [ ]  Write integration tests for the end-to-end role disabling process.
- [ ]  Test all instances for disabling a role (e.g., successful, failed, retry).

**Comment by traderstechie** [comment]
_Slack ID:_ **CHimeziri Obioha**
