### ISSUE TITLE
[FEAT]: Implement Superadmin endpoint for user deletion by ID

### ISSUE THREAD

**Issue by bruce-pain** [hngprojects/hng_boilerplate_python_fastapi_web#240]
## Description

Build an endpoint that allows a superadmin to soft-delete a user by user ID

## Acceptance Criteria

**Endpoint implementation**:

- The endpoint should be accessible at `api/v1/superadmin/users/{:user_id}`
- The endpoint should only accept HTTP `DELETE` requests

**Endpoint security**:

- Only authenticated users can have access to the endpoint
  - The authenticated user must be a superadmin `current_user.is_admin == True`
- Each request to the endpoint must include a valid authentication token in the Authorization header
  - `Authorization: Bearer <token>`

**Validation**:

- The endpoint should check whether the provided `user_id` is valid, that is, the `user_id` exists in the database.

  - If the validation fails (user does not exist):
    - send an error response with HTTP status code of `404` (Not Found)
  - If the validation succeeds (user exists):
    - proceed to perform the user deletion operation
    - send a success response with HTTP status code of `200` (OK) when the user has been successfully soft-deleted

### Sample Request

Route: `DELETE` `/api/v1/superadmin/users/{:user_id}`

- Parameters:

  - `user_id`: UUID string

- **Request Body**: no request body

### Accessing Protected Routes

**Authorization Header**:

- Given a valid token in the Authorization header, the system should allow access and return the requested data when the user accesses a protected route.

  ```json
  {
    "Authorization": "Bearer <token>"
  }
  ```

- When a request is given without an authorization header or with an invalid token, when the user accesses a protected route, the system should return 401 Unauthorized status.

### Sample Response

- **successful response**

  `user_id` is valid and user has successfully been deleted

  ```json
  {
    "status_code": 200,
    "message": "user deleted successfully",
    "data": {}
  }
  ```

- **unsuccessful response**

  - `user_id` is invalid and user notification settings cannot be updated

    ```json
    {
      "status_code": 404,
      "message": "User not found"
    }
    ```

  - The user is unauthorized and cannot access the endpoint

    ```json
    {
      "status_code": 401,
      "message": "Access denied, Unauthorized request"
    }
    ```
  - The user is not a superadnmin

    ```json
    {
      "status_code": 403,
      "message": "Access denied, Superadmin only"
    }
    ```

### Purpose

The endpoint allows superadmin users to safely remove a single user's records from the database

### Requirements

- [x] Ensure an authenticated user is accessing the endpoint
- [x] Ensure that authenticated user is a superadmin
- [x] Develop server-side logic to safely soft-delete a single user
- [x] Ensure that data removal complies with security standards

### Expected Outcome

A secured API endpoint that enables a superadmin to soft-delete a single user

### Tasks

- [x] Implement the endpoint route `api/v1/superadmin/users/{:user_id}`
- [x] Perform the appropriate database operations required to soft-delete a single user
- [x] Ensure that only authorized users can access the endpoint
- [x] Ensure that authorized users are also superadmins
- [x] Implement error handling for scenarios when the user is unauthorized and invalid ID, with the appropriate HTTP status codes
- [x] Ensure the endpoint returns the appropriate response body

### Testing

- Unit testing for the API endpoint, covering authentication logic, removal, error handling etc
- Integration testing to ensure end-to-end functionality.
- Security testing for data protection
