### ISSUE TITLE
### [FEAT]: API Endpoint to Delete All Testimonials #270

### ISSUE THREAD

**Issue by yvonnegichovi** [hngprojects/hng_boilerplate_python_fastapi_web#270]
## Description
We need to implement a `DELETE` endpoint for `/api/v1/testimonials` in our FastAPI application. This endpoint will be responsible for deleting all testimonials from the database.

## Acceptance Criteria
- The `DELETE /api/v1/testimonials` endpoint should delete all testimonials from the database.
- The endpoint should return a success message when testimonials are deleted successfully.
- The endpoint should handle and return appropriate error messages for any failures.
- Only authenticated users with admin permissions can access this endpoint.
- The endpoint should be protected and require authentication.
- The request to the endpoint should include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`

## Endpoint
- HTTP `DELETE` `/api/v1/testimonials`

## API Request Example
```http
DELETE /api/v1/testimonials
Content-Type: application/json
Authorization: Bearer <token>
```

## API Successful Response
```json
{
  "success": true,
  "message": "All testimonials deleted successfully",
  "status_code": 200
}
```

## API Error Responses

- **Bad Request:**
  ```json
  {
    "message": "string",
    "error": "string",
    "status_code": 400
  }
  ```

- **Unauthorized:**
  ```json
  {
    "message": "string",
    "error": "string",
    "status_code": 401
  }
  ```

- **Not Found:**
  ```json
  {
    "message": "string",
    "error": "string",
    "status_code": 404
  }
  ```

- **Server Error:**
  ```json
  {
    "message": "string",
    "error": "string",
    "status_code": 500
  }
  ```

## Tasks
- [ ] Create a new `DELETE` endpoint in the FastAPI application.
- [ ] Implement logic to delete all testimonials from the database.
- [ ] Handle potential errors and exceptions.
- [ ] Ensure only authenticated users with admin permissions can access the endpoint.
- [ ] Write unit tests for the `DELETE` endpoint using pytest.
- [ ] Test the endpoint locally to ensure it works correctly.
- [ ] Document the new endpoint in the API documentation.

## Testing
- [ ] Write unit tests for the delete all testimonials logic.
- [ ] Test various scenarios such as deleting existing testimonials, attempts without proper authentication, and server errors.

## Additional Notes
- Ensure to coordinate with the team and fill out the coordination form as described in the pinned messages.
- Do not push any changes to GitHub until instructed.
- Wait for the update announcement before starting the actual implementation.
