### ISSUE TITLE
[FEAT]: change password - change current user password 

### ISSUE THREAD

**Issue by trevorjob** [hngprojects/hng_boilerplate_python_fastapi_web#284]
## Description
Develop an API endpoint to allow users to change their password using a PATCH request.

## Acceptance Criteria
- The endpoint should be accessible at ```api/v1/auth/me/password```
- The endpoint should accept HTTP PATCH requests.
- The endpoint should be secured to ensure that only authenticated users can change their password.
- Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
- Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: ```Bearer <token>```
- The endpoint should validate the old password before updating to the new password.

## Request
- HTTP Method: PATCH
- Endpoint: /api/v1/me/password
* ***Request Headers :***
```python
{
  "Authorization": "Bearer <token>"
}
```
* ***Request Body: ***
```python
{
   "old_password": "currentPassword123",
  "new_password": "newSecurePassword456"
}
```
* ***Response***
- On a successful password change, the API should return a 200 status code.
- The response body should contain a success message.
 ```python
 {
  "status_code": 200,
  "message": "Password changed successfully"
}
```
- If the old password is incorrect, the API should return a 400 Bad Request status code with an appropriate error message.
```python
{
    "success": false,
    "status_code": 400,
    "message": "Incorrect old password"
}
```
- If any required field is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages.
```python
{
    "success": false,
    "status_code": 422,
    "message": "Invalid input",
    "errors": [
        {
            "type": "missing",
            "loc": [
                "body",
                "old_password"
            ],
            "msg": "Field required",
            "input": {}
        },
        {
            "type": "missing",
            "loc": [
                "body",
                "new_password"
            ],
            "msg": "Field required",
            "input": {}
        }
    ]
}
```
- If the user is not authenticated, the API should return a 401 Unauthorized status code.
```python
{
    "success": false,
    "status_code": 401,
    "message": "Not authenticated"
}
```
### Purpose
Provides a backend service for users to securely change their password.
### Requirements	
- Develop server-side logic to change the user's password.
- Securely handle password updates and validations.
- Ensure compliance with security standards for handling user information.

### Expected Outcome
* The API endpoint allows authenticated users to change their password with appropriate validation and authentication.

### Tasks
- [x] Create an endpoint PATCH /api/v1/users/change-password to change the user's password.
- [x] Implement server-side logic to handle successful and failed password change requests.
- [x] Ensure the user is authenticated before allowing password changes.
- [x] Validate the old password before updating to the new password.
- [x] Write unit tests for changing the user's password.
- [x] Write integration tests for changing the user's password.
- [x] Perform security testing to ensure data protection and compliance.

### Testing
- [x] Write unit tests for backend validation.
- [x] Write integration tests for the end-to-end password change process.
- [x] Perform security testing to ensure data protection and compliance.
- [x] Test various scenarios for changing the password, including valid and invalid passwords and authentication tokens.

###
