### ISSUE TITLE
[FEAT]: PASSWORD RESET: Reset User password of an unauthenticated user

### ISSUE THREAD

**Issue by Myles181** [hngprojects/hng_boilerplate_python_fastapi_web#297]
### Description
 Develop an API endpoint to allow users to reset their password using a POST request.

### Acceptance Criteria
* The endpoint should be accessible at api/v1/auth/password/reset
* The endpoint should accept HTTP POST requests.
* The endpoint should be accessible by anyone, since the user can't login because they don't have the password.
* The endpoint should taking an email and validate if User exists
* The endpoint should send an OTP code to the user's email

### Request
* **HTTP Method**: POST
* **Endpoint**: /api/v1/auth/password/reset
* **Request Body**:
   ```
    {
        "email": "myemail@gmail.com"
    }
   ```

### Response
* If the OTP was successfully sent to the email, endpoint should return  status code as 200
* The response body should contain a success message
```
   {
      "status_code": 200,
      "message": "OTP password reset code sent successfully to {email}"
   }
```
* If a user with the provided email is not found, the API should return a status code of 404 with an appropriate error message
```
   {
      "success": false,
      "status_code": 404,
      "message": "User with this email does not exist."
   }
```
* If OTP code could not be sent successfully, the API should return a status code of 500 Internal Server Error with an appropriate message
```
   {
      "success": false,
      "status_code": 500,
      "message": "OTP code could not send Successfully"
   }
```
* if required field is missing, the API should return a 400 Bad Request status code with appropriate validation error messages.
```
   {
      "success": false,
      "status_code": 400,
      "message": "Invalid input",
      "errors": [
        {
            "type": "missing",
            "loc": [
                "body",
                "email"
            ],
            "msg": "Field required",
            "input": {}
        },
    ]
}
```

### Purpose
Provides a backend service that allows users to reset their password

### Requirements
* Develop server-side logic to reset a user's password via email.
* Securely handle password updates and validations.
* Ensure compliance with security standards for handling user information.

### Expected Outcome
The API endpoint allows users to reset their password without being authenticated.

### Tasks
 - [ ] Create an endpoint POST /api/v1/auth/password/reset to reset the user's password.
 - [ ] Implement server-side logic to handle successful and failed requests.
 - [ ] Write unit tests for sending the otp to the user's email.
 - [ ] Perform security testing to ensure data protection and compliance

### Testing
 - [ ] Write unit tests for backend validation.
 - [ ] Perform security testing to ensure data protection and compliance.
 - [ ] Test various scenarios like if email is valid, if user exists and email is sent successfully.

**Comment by Ali-Peter** [comment]
APPROVED
