### ISSUE TITLE
[FEAT]: Remove member from organization

### ISSUE THREAD

**Issue by IsraelBO17** [hngprojects/hng_boilerplate_python_fastapi_web#342]
## Description
Develop an API endpoint that removes a user from an organization.

## Acceptance Criteria
- Implement an authorization check to ensure that only the organization's owner (org admin) has the ability to remove users.
- The endpoint should be accessible at `/api/v1/organizations/{org_id}/users/{user_id}`.
- The endpoint should accept HTTP DELETE request.
- Upon successful validation, the API should remove the user to the specified organization.

### Response
- On success, the endpoint should return a `200` status code with a success message.
```
{
   "status": "success",
   "message": "User successfully removed from organization"
}
```
- On failure, the endpoint should return a `400` status code with appropriate error messages.
    - **Unauthorized Error Response**
    ```
    {
        "status": "Forbidden",
        "message": "Only Admins can perform this action"
    }
    ```
    - **Object Not Found Error Response**
    ```
    {
        "status": "Not Found",
        "message": "<user/organization> not found"
    }
    ```

## Purpose
Provide a backend service that allows organizations' owners to remove users from organizations.

## Tasks
- [ ] Create the endpoint `/api/v1/organizations/{org_id}/users/{user_id}` with HTTP request method `DELETE`
- [ ] Validate the request param {org_id} and {user_id}
- [ ] Write unit tests for all possible scenarios including successful removal of user from organization, validation errors, and authentication/authorization checks.

**Comment by joboy-dev** [comment]
Approved
