### ISSUE TITLE
[FEAT]: Endpoint for Creating Roles

### ISSUE THREAD

**Issue by SundayMba** [hngprojects/hng_boilerplate_python_fastapi_web#39]
### OS-001: Endpoint for Creating Roles

**Description:**
Implement an endpoint to create roles. This endpoint will allow an admin to create various roles within an organization.

**Acceptance Criteria:**
1. **Endpoint Creation:**
   - Create an API endpoint to allow admins to create new roles within their organization.
   - Ensure that the admins and Super Admins must be authenticated and authorized to access this endpoint.

2. **Database Schema Update:**
   - Update the database schema to include new roles.
3. **Success and Error Handling:**
   - Handle success and error responses appropriately.

4. **Testing and Debugging:**
   - Write unit tests for the role creation endpoint.
   - Perform integration testing to ensure the endpoint works as expected.
   - Debug any issues that arise during testing.

**Purpose:**
To provide an endpoint for admins to create various roles within their organization, ensuring only authorized users can perform this action and maintaining system security.

**Requirements:**
1. **Endpoint Creation:**
   - Implement the endpoint `POST /api/v1/roles` to handle role creation.
   - Validate user input on the server side.
   - Ensure only authenticated and authorized admins can access this endpoint.

2. **Database Schema Update:**
   - Modify the database schema to include the new roles table or update the existing table to include organization references.

3. **Success and Error Handling:**
   - Return appropriate success messages when a role is created successfully.
   - Return error messages when the role creation fails, including appropriate status codes.

4. **Security Measures:**
   - Use HTTPS for secure data transmission.
   - Validate user input on the server side.
   - Encrypt sensitive data as necessary.

**Expected Outcome:**
 - Endpoint to allow admin create various roles

**Tasks:**

- [ ] Create an endpoint (`POST /api/v1/roles`) to handle role creation.
- [ ] Update the database schema to include new roles.
- [ ] Validate user input on the server side.
- [ ] Implement server-side logic to handle successful and failed role creation attempts.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for errors and transaction attempts.
- [ ] Write unit tests for the role creation endpoint.
- [ ] Write integration tests for the role creation process.

**Testing:**

- [ ] Write unit tests for backend validation and transaction handling.
- [ ] Write integration tests for the end-to-end role creation process.
- [ ] Perform security testing to ensure data protection and compliance.
- [ ] Test various scenarios for role creation (e.g., successful, failed, retry).

**Request Body:**
```json
{
  "role_name": "String",
  "organization_id": "String",
  "permission_ids": [
    "String", "String", ...
  ]
}
```
**Response Body (Success)**
```json
{
  "message": "Role created successfully.",
  "status_code": 201
}
```

**Response Body (Error)**
```json
{
  "message": "Role creation failed.",
  "status_code": 400
}
```

**DB diagram**
<img width="672" alt="Screenshot 2024-07-16 at 10 50 51 PM" src="https://github.com/user-attachments/assets/1e54b85a-ea6b-4c1f-b6ca-199fd5ad9498">
