### ISSUE TITLE
[FEAT] Create New Payment

### ISSUE THREAD

**Issue by JoshuaOloton** [hngprojects/hng_boilerplate_python_fastapi_web#446]
## Description
- Develop API endpoint that creates a new payment. The endpoint should accept payment details and process the transaction, returning a confirmation of the payment status.

## Acceptance Criteria
- The endpoint `/api/v1/payments` is accessible via a POST request.
- When valid payment details are provided, the endpoint returns a 201 Created status.
- When invalid payment details are provided, the endpoint returns a 400 Bad Request status.
- On an invalid request, the response body contains an error message indicating the specific validation errors.
- For a failed payment, the response body contains an error message indicating the reason for the failure.
- If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status.
- The response body of an error 500 response contains an error message indicating that an unexpected error occurred.
- Ensure that all unit and integration tests for the create payment endpoint are comprehensive, and verify the functionality correctly.

### Purpose
- This provides a backend service that allows creating and processing payments securely

### Requirements	
- [ ] Implement an endpoint to create payments

### Expected Outcome
- API endpoint that securely processes payments and returns transaction status

### Tasks
- [ ] Create an endpoint /api/v1/payments to accept payment details and process transactions.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for payment attempts and errors.
- [ ] Write unit tests for the create payment endpoint.

## Database Schema
```
Table payments {
  id int [pk, increment] // Primary key
  user_id int [not null, ref: > users.id] // Foreign key
  amount decimal [not null]
  currency varchar [not null]
  status varchar [not null] // completed, pending
  method varchar [not null] // credit card, PayPal
  transaction_id varchar [unique, not null]
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
}
```

## Authorization
- Bearer Token (JWT) required in the Authorization header
- Format: Authorization: Bearer <your_jwt_token>

### Success Response
 - #### Code: 201 CREATED
 - #### Content:
```
{
    "message": "Payment successfully created",
    "success": true,
    "status": 201
}
```

### Error Responses
- #### Code: 400 BAD REQUEST
- #### Content:
```
{
  "error": "Invalid payment details"
}
```

- #### Code 422: UNPROCESSABLE CONTENT / VALIDATION ERROR
#### Content:
```
{
  "errors": {
    "field": "<field>",
    "message": "<message>"
  }
}
```

- #### Code: 500 INTERNAL SERVER ERROR
- #### Content:
```
{
  "error": "An unexpected error occurred"
}
```

### Create New Payment
```
curl -X POST "https://<base-url>/api/v1/payments" \
     -H "Content-Type: application/json" \
     -d '{
  "amount": "5000",
  "currency": "NGN",
  "status": "pending",
  "method": "credit card",
  "transaction_id": "c6842ef66071455645e107479c28674b"
}'
```
