### ISSUE TITLE
[FEAT] GET SINGLE PAYMENT BY ID

### ISSUE THREAD

**Issue by JoshuaOloton** [hngprojects/hng_boilerplate_python_fastapi_web#454]
## Description
- Develop API endpoint that retrieves information about a single payment by its ID. The response should include payment details such as ID, amount, currency, status, and transaction ID.

## Acceptance Criteria
- The endpoint `/api/v1/payments/{payment-id}` is accessible via a GET request.
- The endpoint requires a valid JWT bearer token in the Authorization header for authentication.
- When a valid JWT token and payment ID are provided, the endpoint returns a 200 OK status.
- When an invalid or missing JWT token is provided, the endpoint returns a 401 Unauthorized status.
- When an invalid payment ID format is provided, the endpoint returns a 400 Bad Request status.
- When a payment ID that does not exist is provided, the endpoint returns a 404 Not Found status.
- If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status.
- Ensure that all unit tests for the get single payment endpoint are comprehensive and verify the functionality correctly, including JWT authorization.

## Purpose
- This provides a secure backend service that allows fetching detailed information on a specific payment

## Requirements	
- [ ] Implement an endpoint to view single payment by ID
- [ ] Implement JWT bearer token authorization using the Authorization header
- [ ] Return detailed information on the requested payment
- [ ] Handle situations where payments don't exist
- [ ] Ensure proper error handling and status codes

## Expected Outcome
- Secure API endpoint that returns detailed information on a specific payment, accessible only with valid JWT tokens in the Authorization header

## Tasks
- [ ] Create an endpoint `/api/v1/payments/{payment-id}` to fetch details of a single payment.
- [ ] Implement JWT bearer token authorization middleware that checks the Authorization header.
- [ ] Implement server-side logic to handle successful and failed payment retrieval requests.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for payment retrieval attempts, errors, and authorization failures.
- [ ] Write unit tests for the get single payment endpoint, including authorization header tests.
- [ ] Perform security testing to ensure data protection and proper token validation in the Authorization header.

## Database Schema
```
Table payments {
  id int [pk, increment]
  user_id int [not null]
  amount decimal(10,2) [not null]
  currency varchar(3) [not null]
  status varchar(20) [not null]
  payment_method varchar(50)
  transaction_id varchar(255)
  created_at timestamp [default: current_timestamp]
  updated_at timestamp [default: current_timestamp]
}
```

## Authorization
- Bearer Token (JWT) required in the Authorization header
- Format: Authorization: Bearer <your_jwt_token>

## Request Headers
- Authorization: Bearer <your_jwt_token>

### Success Response
 - #### Code: 200 OK
 - #### Content:
 ```
{
  "payment": {
    "id": "string",
    "user_id": "string",
    "amount": "number",
    "currency": "string",
    "status": "string",
    "payment_method": "string",
    "transaction_id": "string",
    "created_at": "string",
    "updated_at": "string"
  }
}
```

### Error Responses

- #### Code: 401 UNAUTHORIZED
- #### Content:
```
{
    "success": false,
    "status_code": 401,
    "message": "Could not validate credentials"
}
```

- #### Code: 404 NOT FOUND
- #### Content:
```
{
  "error": "Payment not found"
}
```

- #### Code: 500 INTERNAL SERVER ERROR
- #### Content:
```
{
  "error": "An unexpected error occurred"
}
```

### Fetch Single Payment By ID
```
curl -X GET "https://<base-url>/api/v1/payments/12345" \
     -H "Authorization: Bearer <your_jwt_token>"
```
