### ISSUE TITLE
[FEAT] Endpoint to retrieve all comments for a single blog.

### ISSUE THREAD

**Issue by johnson-oragui** [hngprojects/hng_boilerplate_python_fastapi_web#486]
## Description
Implement an endpoint that will enable the retrieval of all comments related or under a single blog.

## Acceptance Criteria
1. **Get all comments for a blog Endpoint**:
   - A new endpoint `GET/api/v1/blogs/{blog_id}/comments?page=2&per_page=20` that retrieves all comments under a blog..
   - The endpoint should be able to retrieve comments for a blog with pagination.
   - The endpoint should not retrieve any comment that is not related to a specific blog

2. **Error Handling**:
   - Handle errors gracefully and provide meaningful error messages.
   - Ensure that database failures, inappropriate queries, and fetch errors are properly managed.

### Purpose
This feature will allow ease in retrieving comments attached to a blog without overloading in case of too large a dataset of comments.

### Requirements	
1. ****:
   - Retrieve a single blog.
   - Retrieve all comments associated with the single blog, if any..

4. **Dependencies**:
   - Ensure the application can list all comments associated with a blog.

**Tasks:**

1. **Retrieve a blog**:
- [ ] Get a single blog.
- [ ] Check for comments attached
- [ ] Retrieve the comments if any

2. **Create  comments Endpoint**:
- [ ] Implement the `/api/v1/blogs/{blog_id}/comments?page=2&per_page=20` endpoint.

3. **Implement Pagination**:
- [ ] Implement a pagination to send comments in batches.
- [ ] Define default values for page and per_page in case the user doesn't provide them.
- [ ] Implement input validation to ensure that page and per_page are valid positive integers.
- [ ] Handle cases where the requested page is out of bounds or the per_page value is too large.

4. **Send the comments**:

- response
```
{
  "page": 1,  // The number of the current page
  "per_page": 10, // defined page size
  "total": 100, // Total number of comments for the blog
  "data": [
    {
      "id": 1,
      "author": "John Doe",
      "content": "This is a comment",
      "created_at": "2023-11-22T10:35:22Z"
    },
    // ... other comments
  ]
}
```

5. **Error Handling and Testing**:
- [ ] Implement error handling for all errors that could occur.
- [ ] Write unit tests and integration tests for the new endpoint and functionalities.

**Database Designs:**
```
Table comments {:
    user_id varchar [ref: > users.id, not null]
    blog_id varchar [ref: > blog_id, not null]
    content varchar [note: “The comment”, not null]
}
```

### Expected Outcome
Every blog would have the comments associate with it listed under it in batches(paginated)

###
