### ISSUE TITLE
[FEAT] Implement create activity-log route

### ISSUE THREAD

**Issue by Goketech** [hngprojects/hng_boilerplate_python_fastapi_web#494]
## Description
Implement a functionality to create activity logs for users. This feature will allow tracking and recording of user activities within the system.

## Acceptance Criteria

- Endpoint is correctly versioned.

-  Create Activity Log Endpoint:
    - Accepts user ID and activity details in the request body.
    - Logs the activity to the database.
    - Responds with a message indicating the activity has been logged successfully.
    - Handles invalid input by responding with a 400 Bad Request status.
 
### Purpose
To maintain a record of user activities within the system for auditing, monitoring, and analytical purposes.

### Expected Outcome
The activity should be logged successfully in the database and a confirmation message should be returned to the user.

### Endpoints

Create Activity Log:
- **Description**: Log a user activity in the system.
- **Endpoint**: GET `/api/v1/activity-logs/create`
- **Request Body**:
```json
{
  "user_id": "12345",
  "activity": "User logged in",
  "timestamp": "2024-07-25T12:34:56Z"
}
```
- **Response (Success)**:
```json
{
  "message": "Activity logged successfully",
  "status_code": 200
}
```
- **Response (Error)**:
```json
{
 "message": "Failed to log activity",
  "status_code": 400
}
```

## Tasks
- [ ] Create the POST `/api/v1/activity-logs/create` endpoint.
- [ ] Implement logic to log the activity to the database.
- [ ] Handle invalid input.
- [ ] Write unit tests for the POST `/api/v1/activity-logs/create` endpoint.
- [ ] Ensure the timestamp is recorded accurately.

## Testing
- Write unit tests to validate the request body and ensure the activity is logged correctly.
- Include integration tests to verify the end-to-end functionality, including database logging and response handling.
