### ISSUE TITLE
[FEAT]: Payments History For Current User

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#500]
## Description
Implement an endpoint to list all payments for the currently logged in user, with pagination.

## Acceptance Criteria
-   It should be a `PROTECTED` endpoint, requiring user authentication.
-   It should be a `GET` request at `/api/v1/payments/current-user/`.
-   It should return all payments for the currently logged-in user and paginate them.
-   It should return basic information about each payment: _(eg: amount, currency, status, method, etc)_
-   **Pagination Info & URL Args**: 
Default number of payments per page: `limit=10`
Default page: `page=1`
Example url `/api/v1/payments/current-user?page=1&limit=10`

## Purpose
To provide users with a means to visualise their payments history once they are properly authenticated.

## Requirements
- [ ] Develop backend logic to fetch and paginate all payments made by the currently logged-in user
- [ ] Follow the _Acceptance Criteria_ detailed above.
- [ ] Test the endpoint for correctness and accuracy.

## Expected Outcome
Properly logged in users should be able to retrieve their payments history seemlessly with the click of a button.

## Tasks
- [ ]  Create endpoint (`GET: /api/v1/payments/current-user?page=1&limit=10`) to handle current user payments history.
- [ ]  Validate the requester to be sure it's a properly authenticated user.
- [ ]  Query the database for all `Payment` made by the current user.
- [ ]  Paginate and return the payments retrieved from the query, based on info in _acceptance criteria_.
- [ ]  Include self explanatory _success message_ if request goes well, or _failure message_, if it doesn't.
- [ ]  Write comprehensive unit tests for the endpoint and dislike operation.

**Example Request [With Auth Token]:**
```
curl -X GET {rootdomain}/api/v1/payments/current-user?page=1&limit=10 \
     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
     -d ....
```

**Response Body [Success]:**
```
{
  "status_code": 200,
  "message": "Payments fetched successfully.",
  "data": {
    "payments": [
        {
        "id": string,
        "user_id": string,
        "amount": float,
        "currency": string,
        "status": string,
        "method": string,
        "transaction_id": string,
        "created_at": datetime
    },
    ...
  ],
    "pagination": {
        "totalItems": int,
        "totalPages": int,
        "currentPage": int
    }
  }
}
```

**Response Body [Errors]:**

- _Unrecognised user:_ `{ "status_code": 401, "message": "Could not validate credentials." }`
- _No payments:_ `{ "status_code": 404, "message": "No payments found for user." }`
- _Failed request:_ `{ "status_code": 400, "message": "Unable to retrieve payments." }`

## Testing:
- [ ]  Write end-to-end backend unit tests for the full payment history request.
- [ ]  Test all possible outcomes for the endpoint (e.g., successful, failed, etc).
