### ISSUE TITLE
Endpoint to Get all Organizations the current-user belongs to

### ISSUE THREAD

**Issue by FreemanBoss** [hngprojects/hng_boilerplate_python_fastapi_web#519]
#### Description
Develop an API endpoint to retrieve all organizations the current user belongs to with proper authentication and validation.

#### Acceptance Criteria
- Endpoint should be accessible at `/api/v1/organizations/current-user`.
- HTTP GET requests should be accepted.
- Endpoint should be secured to allow only authenticated users to retrieve their organizations.
- Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
- Requests must include a valid authentication token in the Authorization header:
  ```
  Authorization: Bearer <token>
  ```

#### Request
No additional parameters are required. The endpoint retrieves organizations based on the authenticated user's information.

#### Response
- On successful retrieval, API should return a `200 OK` status code with a list of organizations the user belongs to.
  ```json
  HTTP/1.1 200 OK
  [
    {
      "org_id": "uuid",
      "name": "string",
      "description": "string"
    }
  ]
  ```
- If the user is not authenticated, return a `401 Unauthorized` status code.
  ```json
  {
    "status_code": 401,
    "message": "User not authenticated"
  }
  ```

#### Error Handling
- If the user is not authenticated, return a `401 Unauthorized` status code.
- If there's a server error, return a `500 Internal Server Error` status code.

#### Purpose
To provide a backend service allowing users to retrieve all organizations they belong to with appropriate authentication.

#### Requirements
- Develop server-side logic to retrieve organizations for the current user.
- Ensure authentication before processing the request.
- Implement proper error handling and status code responses.

#### Expected Outcome
API endpoint allows users to retrieve a list of organizations they belong to with proper authentication and error handling.

#### Task List
- [ ] Create endpoint `GET /api/v1/organizations/current-user` to retrieve organizations.
- [ ] Implement server-side logic for successful and failed retrieval.
- [ ] Ensure authentication check before processing requests.
- [ ] Implement error handling for various scenarios.
- [ ] Write unit tests for organizations retrieval functionality.
- [ ] Perform security testing to validate authentication requirements.

#### Testing
- Write unit tests for the get organizations logic.
- Test various scenarios:
  - Retrieving organizations for an authenticated user.
  - Attempting to retrieve organizations without authentication.
  - Handling server errors.
- Perform security testing to ensure only authenticated users can retrieve their organizations.

**Comment by FreemanBoss** [comment]
- Slack_id: Habeeb Babasulaiman
