### ISSUE TITLE
[FEAT]: Get Contact Endpoint

### ISSUE THREAD

**Issue by SCCSMARTCODE** [hngprojects/hng_boilerplate_python_fastapi_web#536]
### Endpoint Description:
Develop an API endpoint to retrieve messages associated with a specific ID for the contact-us feature.

### Acceptance Criteria:
- [ ] The endpoint should be accessible at `GET api/v1/contact-us/messages/{id}`.
- [ ] Only organization admins with a valid JWT token should be able to access the endpoint.
- [ ] The system should verify if the requester is an authorized organization member or admin based on the decrypted JWT token.
- [ ] Upon a successful request with a valid user ID and proper authorization, return the full name, email, title, and message content for the specified ID with a status code of 200.
- [ ] In case of an unauthorized request, respond with a 401 Unauthorized status.

#### Endpoint:
- **GET** `api/v1/contact-us/messages/{id}`

#### Parameters:
- `id`: string

#### Successful Response:
```json
{
  "status": "success",
  "message": "Message retrieved successfully",
  "data": {
    "full_name": "String",
    "email": "String",
    "title": "String",
    "content": "String"
  }
}
```

#### Error Response:
```json
{
  "status": "error",
  "message": "Unauthorized Access",
  "status_code": 401
}
```

### Purpose:
Provides a backend service enabling authorized users to access and retrieve specific messages related to the contact-us feature.

### Requirements:
- Develop backend logic to retrieve message details based on the provided ID.
- Ensure secure handling of user authentication and authorization.
- Implement error handling for unauthorized access attempts.

### Tasks:
1. **Retrieve Message Logic**:
   - Implement logic to fetch message details based on the provided ID.
   - Verify the requester's authorization status using the JWT token.

2. **Authorization Verification**:
   - Allow access only to authorized organization admins with valid JWT tokens.
   - Decrypt and validate the JWT token to determine the requester's authorization level.

3. **Response Handling**:
   - Return message details including full name, email, title, and content upon successful authorization.
   - Provide an appropriate error response for unauthorized access attempts.

### Tests:
- [ ] Write unit tests for the `GET api/v1/contact-us/messages/{id}` endpoint.
- [ ] Include tests to validate authorization logic and response structures.
- [ ] Write integration tests to ensure the endpoint functions correctly in the context of message retrieval.
- [ ] Test both authorized and unauthorized scenarios to validate endpoint behavior.
