### ISSUE TITLE
feat: endpoint to delete products by ID

### ISSUE THREAD

**Issue by bruce-pain** [hngprojects/hng_boilerplate_python_fastapi_web#560]
## Description

Build an endpoint that allows a user to delete a product by product ID. Product must belong to organisation which the user belongs in.

## Acceptance Criteria

**Endpoint implementation**:

- The endpoint should be accessible at `api/v1/products/{:product_id}`
- The endpoint should only accept HTTP `DELETE` requests

**Endpoint security**:

- Only authenticated users can have access to the endpoint
- Each request to the endpoint must include a valid authentication token in the Authorization header
  - `Authorization: Bearer <token>`

**Validation**:

- The endpoint should check whether the provided `product_id` is valid, that is, the `product_id` exists in the database.

  - If the validation fails (product does not exist):
    - send an error response with HTTP status code of `404` (Not Found)
  - If the validation succeeds (product exists):
    - proceed to perform the product deletion operation
    - send a success response with HTTP status code of `204` (No Content) when the product has been successfully deleted

### Sample Request

Route: `DELETE` `/api/v1/products/{:product_id}`

- Parameters:

  - `product_id`: UUID string

- **Request Body**: no request body

### Accessing Protected Routes

**Authorization Header**:

- Given a valid token in the Authorization header, the system should allow access and return the requested data when the user accesses a protected route.

  ```json
  {
    "Authorization": "Bearer <token>"
  }
  ```

- When a request is given without an authorization header or with an invalid token, when the user accesses a protected route, the system should return 401 Unauthorized status.

### Sample Response

- **successful response**

  `product_id` is valid and user has successfully been deleted

  Status Code: `204: NO CONTENT`

- **unsuccessful response**

  - `user_id` is invalid and user notification settings cannot be updated

    ```json
    {
      "status_code": 404,
      "message": "Product not found"
    }
    ```

  - The user is unauthorized and cannot access the endpoint

    ```json
    {
      "status_code": 401,
      "message": "Not Authenticated"
    }
    ```

  - The user is unauthorized and cannot access the endpoint

    ```json
    {
      "status_code": 400,
      "message": "You are not a member of this organization"
    }
    ```

### Purpose

The endpoint allows users to safely remove a single product's records from the database

### Requirements

- [ ] Ensure an authenticated user is accessing the endpoint
- [ ] Ensure that authenticated user belongs to the same organisation as the product
- [ ] Develop server-side logic to safely delete a single product
- [ ] Ensure that data removal complies with security standards

### Expected Outcome

A secured API endpoint that enables a user to delete a single product

### Tasks

- [ ] Implement the endpoint route `api/v1/products/{:product_id}`
- [ ] Perform the appropriate database operations required to delete a single product
- [ ] Ensure that only authorized users can access the endpoint
- [ ] Ensure that authenticated user belongs to the same organisation as the product
- [ ] Implement error handling for scenarios when the user is unauthorized and invalid ID, with the appropriate HTTP status codes
- [ ] Ensure the endpoint returns the appropriate response body

### Testing

- Unit testing for the API endpoint, covering authentication logic, removal, error handling etc
- Integration testing to ensure end-to-end functionality.
- Security testing for data protection
