### ISSUE TITLE
[FEAT] Add endpoint to fetch all users for super admin

### ISSUE THREAD

**Issue by johnson-oragui** [hngprojects/hng_boilerplate_python_fastapi_web#583]
## Description
implement an endpoint for the super admin to be able to retrieve users from the database. The endpoint would be paginated. default value for page is 1, and default value for page size is 10.

## Acceptance Criteria
1. **Google OAuth2 Login Endpoint**:
   - A new endpoint `GET /api/v1/users?page=1&per_page=10` that retrieves all users for the super admin.
   - The endpoint should handle pagination.
   - The endpoint should be able to retrieve users from the oldest.

2. **Error Handling**:
   - Handle errors gracefully and provide meaningful error messages to the user.
   - Handle errors when per_page params is more than default value.

### Purpose
This feature will allow the super admin to retrieve all users registered.

### Requirements	
1. **Create a route for the endpoint**:
   - The route will be protected, and only the super admin can access this route

2. **Configuration**:
   - No configuration is needed, as the route will use the existing configurations.

4. **Response**:
   - Ensure the data returned is not too large.

**Tasks:**

- [ ] Implement the GET `/api/v1/users` endpoint.
- [ ] Use the params to get the number of users if provided.
- [ ] use Services class to implement the methods for the functionalities.

```
{
    "message": "Users successfully retrieved",
    "status_code": 200,
    "status": "success",
    "page": 1,
    "per_page": 10,
    "total": 4,
    "data": [
        {
            "id": "066a9334-df01-75fd-8000-e5bb10db8883",
            "email": "user2@example.com",
            "first_name": "User",
            "last_name": "Two",
            "is_active": true,
            "is_deleted": false,
            "is_verified": false,
            "is_super_admin": false,
            "created_at": "2024-07-30T19:39:10.720519+01:00",
            "updated_at": "2024-07-30T19:39:10.720519+01:00"
        },
        {
            "id": "066a9334-e4f5-7249-8000-5fb91854efa6",
            "email": "user3@example.com",
            "first_name": "User",
            "last_name": "Three",
            "is_active": true,
            "is_deleted": false,
            "is_verified": false,
            "is_super_admin": false,
            "created_at": "2024-07-30T19:39:10.720519+01:00",
            "updated_at": "2024-07-30T19:39:10.720519+01:00"
        },
        {
            "id": "066a9334-d2c6-7eea-8000-cfed3cfb4e3e",
            "email": "admin@example.com",
            "first_name": "admin",
            "last_name": "admin",
            "is_active": true,
            "is_deleted": false,
            "is_verified": false,
            "is_super_admin": true,
            "created_at": "2024-07-30T19:39:10.720519+01:00",
            "updated_at": "2024-07-30T19:39:10.720519+01:00"
        },
        {
            "id": "066a7c38-761e-7630-8000-57a5779118e4",
            "email": "email@gmail.com",
            "first_name": "first",
            "last_name": "last",
            "is_active": true,
            "is_deleted": false,
            "is_verified": false,
            "is_super_admin": true,
            "created_at": "2024-07-29T17:29:59.382729+01:00",
            "updated_at": "2024-07-29T17:29:59.382729+01:00"
        }
    ]
}
```
### Expected Outcome
The super admin will be able to retrieve all users and access the targeted information.

###
