### ISSUE TITLE
feat: endpoint to create new products

### ISSUE THREAD

**Issue by bruce-pain** [hngprojects/hng_boilerplate_python_fastapi_web#600]
## Description

Build an endpoint that allows a user to create a new product.

## Acceptance Criteria

**Endpoint implementation**:

- The endpoint should be accessible at `api/v1/products/{:org_id}`
- The endpoint should only accept HTTP `POST` requests

**Endpoint security**:

- Only authenticated users can have access to the endpoint
- Each request to the endpoint must include a valid authentication token in the Authorization header
  - `Authorization: Bearer <token>`

**Validation**:

- This endpoint validates the request body before creation of a new product
- The endpoint should check whether the provided `org_id` is valid, that is, the `org_id` exists in the database.

  - If the validation fails (org does not exist):
    - send an error response with HTTP status code of `404` (Not Found)
  - If the validation succeeds (org exists):
    - proceed to create a new product belonging to the org
    - send a success response with HTTP status code of `201` (Created) when the product has been successfully created

### Sample Request

Route: `POST` `/api/v1/products/{:org_id}`

- **parameters**:
  `org_id`: UUID string

- **Request Body**:

  ```json
  {
    "name": "Microwave Oven",
    "quantity": 3,
    "price": 459.99,
    "category": "Electronics",
    "image_url": "some-random-link.com"
  }
  ```

### Accessing Protected Routes

**Authorization Header**:

- Given a valid token in the Authorization header, the system should allow access and return the requested data when the user accesses a protected route.

  ```json
  {
    "Authorization": "Bearer <token>"
  }
  ```

- When a request is given without an authorization header or with an invalid token, when the user accesses a protected route, the system should return 401 Unauthorized status.

### Sample Response

- **successful response**

  Status Code: `201: Created`

  ```json
  {
    "success": true,
    "status_code": 201,
    "message": "Product created successfully",
    "data": {
      "id": "ecb968ce-f7e0-4ff9-913b-0c8dbe9d3f46",
      "name": "Microwave Oven",
      "quantity": 3,
      "price": 459.99,
      "category": "Electronics",
      "image_url": "some-random-link.com",
      "description": null,
      "status": "in stock",
      "created_at": "2024-07-29T19:51:39.004Z",
      "updated_at": "2024-07-29T19:51:39.004Z"
    }
  }
  ```

- **unsuccessful response**

  - The user is unauthenticated and cannot access the endpoint

    ```json
    {
      "status_code": 401,
      "message": "Not Authenticated"
    }
    ```

  - The request body contains invalid fields

    ```json
    {
      "status_code": 400,
      "message": "Bad request"
    }
    ```

  - `org_id` is invalid

    ```json
    {
      "status_code": 404,
      "message": "Organisation not found"
    }
    ```

### Purpose

The endpoint allows users to create a single product record in the database

### Requirements

- [x] Ensure an authenticated user is accessing the endpoint
- [x] Develop server-side logic to safely create a single product
- [x] Ensure that data creation complies with security standards

### Expected Outcome

A secured API endpoint that enables a user to create a single product

### Tasks

- [x] Implement the endpoint route `api/v1/products/{:org_id}`
- [x] Perform the appropriate database operations required to create a single product
- [x] Ensure that only authorized users can access the endpoint
- [x] Implement error handling for scenarios when the user is unauthorized and invalid data, with the appropriate HTTP status codes
- [x] Ensure the endpoint returns the appropriate response body

### Testing

- Unit testing for the API endpoint, covering authentication logic, removal, error handling etc
- Integration testing to ensure end-to-end functionality.
- Security testing for data protection
