### ISSUE TITLE
[FEAT] Endpoint for the super Admin to create a user

### ISSUE THREAD

**Issue by johnson-oragui** [hngprojects/hng_boilerplate_python_fastapi_web#616]
## Description
implement POST api/v1/users which will allow the Super Admin to create a new User.

## Acceptance Criteria
1. **Add a create User Endpoint**:
   - A new endpoint `POST api/v1/users` that allows the super admin to create users.

2. **Protect route For Super Admin**:
   - Add functionality to restrict non Super Admin users from accessing the endpoint.

3. **Error Handling**:
   - Handle errors gracefully and provide meaningful error messages to the user.
   - Ensure that authentication failures, token exchange errors, and user information fetch errors are properly managed.

### Purpose
This feature will allow the Super Admin to create new users.

### Requirements	
1. **Create The route**:
   - Create the POST Route that receives request from the super admin.

2. **Functionality**:
   - Add functionalities using the user service class to create a new user.
   - Return the newly created user.

**Tasks:**

1. **Create Route**:
- [ ] Create a route to handle the incoming POST request.

2. **Create users Endpoint**:
- [ ] Implement the POST `/api/v1/users` endpoint.
- [ ] Implement token storage and management.

6. **User Information Update Logic**:
- [ ] Implement logic to Add user to the database.

7. **Error Handling and Testing**:
- [ ] Implement error handling for all authentication and invalid fields.
- [ ] Write unit tests (pytest) and integration tests for all new endpoints and functionalities.

- response
```
{
  "status": "success",
  "status_code": 201,
  "message": "User created successfully",
  "user": {
    "id": "iomdi2j982j-309vkq309-3qrvq3v-34ijmqi9i3uvn3",
    "email": "johnson.oragui@gmail.com",
    "first_name": "Johnson Oragui",
    "last_name": "Johnson",
    "is_verified": "true",
    "is_active": "true",
    "is_deleted": "false",
    "created_at": "datetime",
    "updated_at": "datetime"
  }
}
```
- error response
```
{
  "status": "success",
  "status_code": 401,
  "message": "Un-Authorized",
}
```
### Expected Outcome
The Super Admin will be able to create a new user.

###
