### ISSUE TITLE
[FEAT]: Job Details - GET job details

### ISSUE THREAD

**Issue by trevorjob** [hngprojects/hng_boilerplate_python_fastapi_web#63]
## Description
Develop an API endpoint to retrieve details of a specific job by its ID.

## Acceptance Criteria
- The endpoint should be accessible at ```api/v1/jobs/:id```
- The endpoint should accept HTTP GET requests.
- The endpoint should be secured to ensure that only authenticated users can access job details.
- Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
- Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: ```Bearer <token>```

## Request
- HTTP Method: GET
- Endpoint: /api/v1/jobs/:id
* ***Request Headers :***
```python
{
  "Authorization": "Bearer <token>"
}
```
* ***Response***
- On a successful retrieval of job details the api should return 200 status code
- The response body should contain all of the job details. The salary is optional 
 ```python
{
  "id": 1,
  "job_title": "Job Title",
  "description": "Job Description",
  "location": "Location",
  "salary": 1000.0, # salary is optional 
  "employer": "Employer Name",
  "created_at": "2024-07-17T12:00:00Z",
  "updated_at": "2024-07-17T12:00:00Z"
}
```
- If any required field is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages.
```python
{
  "status_code": 400,
  "message": ["id must be a string"],
  "error": "Bad Request"
}
```
- if the job is not found, the API should return a 404 Not Found status code with appropriate validation error messages.
```python
{
  "status_code": 404,
  "message": "Job not found",
  "error": "Not Found"
}
```
### Purpose
Provides a backend service to retrieve the details of a specific job by its ID.
### Requirements	
- Develop server-side logic to retrieve job details by ID.
- Securely fetch job details from the database.
- Ensure compliance with security standards for handling user information.

### Expected Outcome
* The API endpoint allows retrieving details of a specific job by its ID with appropriate validation and authentication.

### Tasks
- [ ] Create an endpoint GET /api/v1/jobs/:id to retrieve job details.
- [ ] Implement server-side logic to handle successful and failed retrieval requests.
- [ ] Ensure the user has the proper permissions to view job details.
- [ ] Write unit tests for retrieving job details.
- [ ] Write integration tests for retrieving job details.
- [ ] Perform security testing to ensure data protection and compliance.

### Testing
- [ ] Write unit tests for backend validation.
- [ ] Write integration tests for the end-to-end retrieval of job details.
- [ ] Perform security testing to ensure data protection and compliance.
- [ ] Test various scenarios for retrieving job details, including valid and invalid job IDs and authentication tokens.

###

**Additional context**
