### ISSUE TITLE
[FEAT] Create New Product Category

### ISSUE THREAD

**Issue by JoshuaOloton** [hngprojects/hng_boilerplate_python_fastapi_web#645]
# Create Product Category API Endpoint

## Description

Develop an API endpoint that creates a new product category. The endpoint should accept category name and create a new category returning a confirmation of the category creation status.

## Acceptance Criteria

- The endpoint `/api/v1/products/categories/{org_id}` is accessible via a POST request.
- When valid category details are provided, the endpoint returns a 201 Created status.
- When invalid category details are provided, the endpoint returns a 400 Bad Request status.
- On an invalid request, the response body contains an error message indicating the specific validation errors.
- If the organization ID is invalid or not found, the endpoint returns a 404 Not Found status.
- If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status.
- The response body of an error 500 response contains an error message indicating that an unexpected error occurred.
- Ensure that all unit and integration tests for the create product category endpoint are comprehensive and verify the functionality correctly.

### Purpose

- This provides a backend service that allows creating product categories.

### Requirements

- [ ] Implement an endpoint to create product categories.

### Expected Outcome

- API endpoint that securely creates product categories and returns a success or failure creation status.

### Tasks

- [ ] Create an endpoint `/api/v1/products/categories/{org_id}` to accept category details and create new categories.
- [ ] Implement authorization to ensure only authorized users can create categories.
- [ ] Implement logging for category creation attempts and errors.
- [ ] Write unit tests for the create product category endpoint.

## Database Schema
```sql
Table product_categories {
  id int [pk, increment] // Primary key
  name varchar [not null]
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp
}
```

## Authorization
- Bearer Token (JWT) required in the Authorization header
- Format: Authorization: Bearer <your_jwt_token>

### Success Response
 - #### Code: 201 CREATED
 - #### Content:
```json
{
    "message": "Product category successfully created",
    "success": true,
    "status": 201,
    "category": {
        "id": 1,
        "name": "Electronics",
        "description": "Electronic devices and accessories",
        "parent_category_id": null
    }
}
```

### Error Responses
 - #### Code: 400 BAD REQUEST
 - #### Content:
 ```
 {
  "error": "Invalid category details"
}
 ```
 
 - #### Code: 422: UNPROCESSABLE CONTENT / VALIDATION ERROR
 - #### Content:
 ```
 {
  "errors": {
    "field": "<field>",
    "message": "<message>"
  }
}
```

 - #### Code: 404 NOT FOUND
 - #### Content:
 ```
{
  "error": "Organization not found"
}
```

 - #### Code: 500 INTERNAL SERVER ERROR
 - #### Content:
 ```
{
  "error": "An unexpected error occurred"
}
```

### Create New Category

```
curl -X POST "https://<base-url>/api/v1/products/categories/123" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer <your_jwt_token>" \
     -d '{
  "name": "Electronics"
}'
```
