### ISSUE TITLE
[FEAT]: Get All Products In Dashboard For Super Admins

### ISSUE THREAD

**Issue by chimeziriobioha** [hngprojects/hng_boilerplate_python_fastapi_web#664]
## Description
Implement an endpoint to return all products in the `/dashboard` route, for super admins.

## Acceptance Criteria
-   It should be a `PROTECTED` endpoint, accessible to **only super admins**.
-   It should be a `GET` request at `/api/v1/dashboard/products`.
-   It should return basic information about all products as a list of dictionaries.

## Purpose
To allow supper admins view products from the` /dashboard` route

## Requirements
- [ ] Develop backend logic to fetch all products, arrange and return it
- [ ] Follow the _Acceptance Criteria_ detailed above.
- [ ] Test the endpoint for correctness and accuracy.

## Expected Outcome
Vetted **super admins** should be able to retrieve all products seemlessly with the click of a button.

## Tasks
- [ ]  Create endpoint (`GET: /api/v1/dashboard/products`) to handle the request.
- [ ]  Validate the requester to be sure it's a properly authenticated **super admin**.
- [ ]  Query the database for all `Product`.
- [ ]  Return the products retrieved from the query, based on info in _acceptance criteria_.
- [ ]  Include self explanatory _success message_ if request goes well, or _failure message_, if it doesn't.
- [ ]  Write comprehensive unit tests for the operation.

**Example Request [With Auth Token]:**
```
curl -X GET {rootdomain}/api/v1/dashboard/products \
     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
     -d ....
```

**Response Body [Success]:**
```
{
  "status_code": 200,
  "success": true,
  "message": "Products fetched successfully",
  "data": [
    {
      "name": "string",
      "description": "string",
      "price": "string",
      "category": "string",
      "quantity": 0,
      "image_url": "string",
      "archived": true,
      "created_at": "2024-08-02T13:35:48.913Z"
    },
    ...
  ]
}
```

**Response Body [Errors]:**

- _Unrecognised user:_ `{ "status_code": 401, "message": "Could not validate credentials." }`
- _Missing authentication:_ `{ "status_code": 401, "message": "Not authenticated." }`

## Testing:
- [ ]  Write end-to-end backend unit tests for the full products list request.
- [ ]  Test all possible outcomes for the endpoint (e.g., successful, failed, etc).
