### ISSUE TITLE
[FEAT]: Get Single Product In Dashboard For Super Admins

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#665]
## Description
Implement an endpoint to return a single product in the `/dashboard` route, for super admins.

## Acceptance Criteria
-   It should be a `PROTECTED` endpoint, accessible to **only super admins**.
-   It should be a `GET` request at `/api/v1/dashboard/products/{product_id}`.
-   It should return basic information about the product as a dictionaries.

## Purpose
To allow supper admins view a product from the` /dashboard` route

## Requirements
- [ ] Develop backend logic to fetch the product, using the `product_id` provided, and return it
- [ ] Follow the _Acceptance Criteria_ detailed above.
- [ ] Test the endpoint for correctness and accuracy.

## Expected Outcome
Vetted **super admins** should be able to retrieve any product detail seemlessly with the click of a button.

## Tasks
- [ ]  Create endpoint (`GET: /api/v1/dashboard/products/{product_id}`) to handle the request.
- [ ]  Validate the requester to be sure it's a properly authenticated **super admin**.
- [ ]  Query the database for the `Product`.
- [ ]  Return the product retrieved from the query, based on info in _acceptance criteria_.
- [ ]  Include self explanatory _success message_ if request goes well, or _failure message_, if it doesn't.
- [ ]  Write comprehensive unit tests for the operation.

**Example Request [With Auth Token]:**
```
curl -X GET {rootdomain}/api/v1/dashboard/products/{product_id} \
     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
     -d ....
```

**Response Body [Success]:**
```
{
  "status_code": 200,
  "success": true,
  "message": "Product fetched successfully",
  "data": {
      "name": "string",
      "description": "string",
      "price": "string",
      "category": "string",
      "quantity": 0,
      "image_url": "string",
      "archived": true,
      "created_at": "2024-08-02T13:35:48.913Z"
    }
}
```

**Response Body [Errors]:**

- _Unrecognised user:_ `{ "status_code": 401, "message": "Could not validate credentials." }`
- _Missing authentication:_ `{ "status_code": 401, "message": "Not authenticated." }`
- _Wrong ID:_ `{ "status_code": 404, "message": "Product not fount." }`

## Testing:
- [ ]  Write end-to-end backend unit tests for the product detail request.
- [ ]  Test all possible outcomes for the endpoint (e.g., successful, failed, etc).
