### ISSUE TITLE
[FEAT]: Get All Products COUNT In Dashboard For Super Admins

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#666]
## Description
Implement an endpoint to return all products COUNT in the `/dashboard` route, for super admins.

## Acceptance Criteria
-   It should be a `PROTECTED` endpoint, accessible to **only super admins**.
-   It should be a `GET` request at `/api/v1/dashboard/products/count`.
-   It should return the `count` information in a dictionaries along with other request details.

## Purpose
To allow supper admins get all products count from the` /dashboard` route

## Requirements
- [ ] Develop backend logic to return all products count
- [ ] Follow the _Acceptance Criteria_ detailed above.
- [ ] Test the endpoint for correctness and accuracy.

## Expected Outcome
Vetted **super admins** should be able to retrieve all products count seemlessly with the click of a button.

## Tasks
- [ ]  Create endpoint (`GET: /api/v1/dashboard/products/count`) to handle the request.
- [ ]  Validate the requester to be sure it's a properly authenticated **super admin**.
- [ ]  Query the database for all `Product`, and retrieve the count.
- [ ]  Return the count based on info in _acceptance criteria_.
- [ ]  Include self explanatory _success message_ if request goes well, or _failure message_, if it doesn't.
- [ ]  Write comprehensive unit tests for the operation.

**Example Request [With Auth Token]:**
```
curl -X GET {rootdomain}/api/v1/dashboard/products/count \
     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
     -d ....
```

**Response Body [Success]:**
```
{
  "status_code": 200,
  "success": true,
  "message": "Products count fetched successfully",
  "data": {
    "count": 0
  }
}
```

**Response Body [Errors]:**

- _Unrecognised user:_ `{ "status_code": 401, "message": "Could not validate credentials." }`
- _Missing authentication:_ `{ "status_code": 401, "message": "Not authenticated." }`

## Testing:
- [ ]  Write end-to-end backend unit tests for the products count request.
- [ ]  Test all possible outcomes for the endpoint (e.g., successful, failed, etc).
