### ISSUE TITLE
[TEST, FIX, REFACTOR]: Improve Dislike Blog Post Test And Implementation

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#667]
## Description:
Improve the **unittest** and **implementation** of the Dislike Blog Post feature _([Issue 275](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/275) and [PR 491](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/491))_ at endpoint: `/api/v1/blog/:{blog_id}/dislike`.
***

## Update Details:

- Test the value of `data` _[BlogDislike object data]_ returned from a successful request, for accuracy.
    * _Sample Return Value:_ 
      ```
      {
        "status_code": int,
        "message": String,
        "data": {
           "id": "string",
           "blog_id": "string",
           "user_id": "string",
           "ip_address": "string",
           "created_at": "2024-07-28T10:17:40.003Z"
        }
      }
      ```
   This fix adds test for the entire content of the dict value of `data`
- Record `client IP address` for every successful dislike request
- Change response schema from `BlogDislikeResponse` to `BlogLikeDislikeResponse` so that like/dislike requests can utilise it. _This conforms with the DRY code principle_.
***

## Acceptance Criteria:

-   Stick to the changes mention in _update details_ above.
-   Do not change other people's code without appropriate permission.
***

## Purpose
To have a quality code base that's well tested and easy to maintain.
***

## Tasks:
 
- [ ]  Update file `/api/tests/v1/blog/test_dislike_blog_post.py` with proposed improvements to the tests
- [ ]  Update file `/api/v1/schemas/blog.py` to change `BlogDislikeResponse` to `BlogLikeDislikeResponse`.
- [ ]  Add new function `get_ip_address` in new file `/api/v1/utils/client_helpers.py`, to retrieve client IP address
- [ ]  Update function `dislike_blog_post` in file `/api/v1/routes/blog.py`, to add `ip_address` to every new instance of `BlogDislike` and make use of `BlogLikeDislikeResponse`

## Testing:

- [ ]  Write test for all updates requiring one
- [ ]  Ensure all existing tests passes _[without tampering]_, alongside the new ones added
