### ISSUE TITLE
[TEST, FIX]: Improve Dashboard Products Tests And Implementation

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#668]
## Description:
Improve the **unittest** and **implementation** of the Dashboard Products Fetching features _([PR 654](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/654) and Issues [664](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/664),  [665](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/665),  [666](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/666))_ at endpoints: `/dashboard/product/{product_id}`, `/dashboard/products`, and `/dashboard/products/count`.
***

## Update Details:

- Test the value of `data` _[Product object data]_ returned from a successful requests, for accuracy.
    * _Sample Return Value:_ 
      ```
      {
        "status_code": int,
        "message": String,
        "data": {
           "id": "string",
           "name": "string",
           "description": "string",
           "price": "string",
           "quantity": 0,
           "image_url": "string",
           "archived": true,
           "category_name": "string",
           "organization_name": "string",
           "created_at": "2024-08-04T21:26:28.055Z",
           "category_id": "string",
           "organization_id": "string"
          }
        }
      }
      ```
   This fix adds test for the entire content of the dict value of `data` and splits the current `/api/tests/v1/dashboard/test_get_products.py` file into three different file 
- Paginate the result of `/dashboard/products`
- Update `schemas/dashboard` file to accommodate pagination.
- Add new function to `utils/pagination.py` file.
- Update `services.product.ProductService.fetch_all` to include pagination query handling, and add two new helper methods
***

## Acceptance Criteria:

-   Stick to the changes mention in _update details_ above.
-   Do not change other people's code without appropriate permission.
***

## Purpose
To have a quality code base that's well tested and easy to maintain.
***

## Tasks:
 
- [ ]  Update file `/api/tests/v1/dashboard` with proposed improvements to the tests
- [ ]  Update schemas in file `/api/v1/schemas/dashboard.py` to accommodate pagination.
- [ ]  Add new function `get_pagination_details` in file `/api/v1/utils/pagination.py`, to organise pagination details 
- [ ]  Add methods `dynamic_product_dict` and `fetch_and_dictize` to `services.product.ProductService`, to handle pagination 
- [ ]  Update routes functions `get_products`, `get_products_count`, and `get_product` in `/api/v1/routes/product.py`, to add pagination and make use of newly added helper functions/methods.
- [ ]  Update error messages

## Testing:

- [ ]  Write test for all updates requiring one
- [ ]  Ensure all existing tests passes _[without tampering]_, alongside the new ones added
