### ISSUE TITLE
API to fetch single testimonial 

### ISSUE THREAD

**Issue by FreemanBoss** [hngprojects/hng_boilerplate_python_fastapi_web#68]
## Description
Fetch a single testimonial by Id. 

## Acceptance Criteria

- The endpoint should be accessible at `GET /api/v1/testimonials/:testimonial_id`
- User should be authenticated to access the endpoint.
- The endpoint should return a `404` status code if the testimonial does not exist.
- The endpoint should return a `401` status code if the user is not authenticated.
- The endpoint should return a `200` status code if the testimonial is fetched.
- The endpoint should return a single testimonial.
- The endpoint must accept access token `Authorization: Bearer: <token>`

### Purpose

Be able to view a single testimonial and leave a comment. 

### Requirements

- Implement API endpoint for single testimonial.
- Testimonial should be fetched successfully if it exists. 
- Handle unexpected errors and return the appropriate status code.
- User must be authenticated to access this endpoint.
- The endpoint must accept access token `Authorization: Bearer: <token>`

### API Endpoint

```http
GET /api/v1/testimonials/: testimonial_id
```

#### Response

```json
{
  "message": "Testimonial fetched successfully",
  "status_code": 200,
  "data": {
    "id": "String",
    "author": "String",
    "testimonial": "String",
    "comments": Array, 
    "created_at": "DateTime",
  }
}
```

#### Error Responses

```json
{
  "status_code": 404,
  "message": "Testimonial not found"
}
```

```json
{
  "status_code": 401,
  "message": "Unauthorized "
}
```

### Expected Outcome

User should be able to view Single Testimonial and all the comments associated with it. 

### Tasks
- [ ] Develop API endpoint to view Testimonial.
- [ ] Return proper error cases.
- [ ] Write tests for the API endpoint.

### Testing

- Unit tests should be written for the API endpoint.
- Integration tests should be written for the API endpoint.

**Comment by FreemanBoss** [comment]
Reference ticket: hngprojects/hng_boilerplate_nestjs#255
Slack id: - Habeeb Babasulaiman
