### ISSUE TITLE
[FEAT]: Endpoint To Like A Blog Post

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#690]
### Description:
Implement an endpoint to enable users and readers to like a blog post.

## Acceptance Criteria:

-   It should be a `PROTECTED` endpoint, requiring authentication.
-   It should be a `POST` request at `/api/v1/blog/:{blog_id}/like`.
-   It should persist all valid blog **like** to the database and return appropriate message to the user.
-   It should allow a user to like a blog post ONLY once.
***

## Purpose
To enable a blog post readers to express their like of any particular post.

## Requirements

- [ ] Develop server-side logic to add **like** to a blog post following _acceptance criteria_ above
- [ ] Test the endpoint for correctness and accuracy.

## Expected Outcome:
Viewers should be able to like a blog post seemlessly with the click of a button.
***

## Tasks:
 
- [ ]  Create endpoint (`POST: /api/v1/blog/:{blog_id}/like`) to handle likes.
- [ ]  Validate `blog_id` provided on the server side, and use it to access the `Blog` post
- [ ] Create a new `BlogLike` object with a one-to-many relationship to the `User` and `Blog` in the request.
- [ ]  Return self explanatory _success response_ if request goes well, or _failure response_, if it doesn't.
- [ ]  Write comprehensive unit tests for the endpoint and like operation.

**Required Database Table**
```
Table blog_likes {
  id varchar [primary key]
  blog_id varchar
  user_id varchar
  ip_address varchar [optional]
  created_at datetime
}
```

**Example Request [With Auth Token]:**
```
curl -X POST {rootdomain}/api/v1/blog/:{blog_id}/like \
     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
     -d ....
```

**Response Body [Success]:**
```
{
  "status_code": 200,
  "message": "Like recorded successfully.",
  "data": {
    "id": "string",
    "blog_id": "string",
    "user_id": "string",
    "ip_address": "string",
    "created_at": "2024-07-28T10:17:40.003Z"
  }
}
```

**Response Body [Errors]:**

- _Unrecognized user:_ `{ "status_code": 401, "message": "Could not validate credentials." }`
- _Already liked blog:_ `{ "status_code": 403, "message": "You have already liked this blog post" }`
- _Invalid blog ID:_ `{ "status_code": 404, "message": "Blog post not found." }`
- _Failed like:_ `{ "status_code": 400, "message": "Unable to record like." }`
***

## Testing:

- [ ]  Write end-to-end backend unit tests for the full like process.
- [ ]  Test all possible outcomes and reactions for like (e.g., successful, failed, etc).
