### ISSUE TITLE
[FEAT]: Get Users by Role

### ISSUE THREAD

**Issue by JoshuaOloton** [hngprojects/hng_boilerplate_python_fastapi_web#706]
## Description
- Develop an endpoint for the admin to get all users assigned to a specific role in an organization. The response includes user details such as ID, name, email, and role.

## Acceptance Criteria

- The endpoint `/api/v1/users/{role_id}/users` is accessible via a GET request.
- The endpoint requires valid authentication.
- The authenticated user must have the "admin" or "owner" role to access the endpoint.
- When a valid role is provided and the authenticated user is an admin, the endpoint returns a 200 OK status.
- When an invalid role format is provided, the endpoint returns a 400 Bad Request status.
- On an invalid request, the response body contains an error message indicating the invalid role format.
- When the authenticated user does not have the "admin" role, the endpoint returns a 403 Forbidden status.
- For a role that does not exist, the endpoint returns a 404 Not Found status.
- The response body of an error 500 response contains an error message indicating that an unexpected error occurred.
- Ensure that all unit  tests for the fetch users by role endpoint are comprehensive, and verify the functionality correctly.

### Purpose
- This provides a backend service that allows fetching a list of users based on their role.

### Requirements	

- [ ] Implement an endpoint to view users by role
- [ ] Return detailed information on users
- [ ] Handle situations where users or roles don't exist
- [ ] Request must requires admin-level authentication. 
- [ ] The request must include a valid access token. 

### Expected Outcome
- The admin successfully receives a list of users assigned the specified role within the organization. If the organization or role does not exist, or if the admin lacks permissions, the appropriate error message is returned.

### Tasks

- [ ] Create an endpoint /api/v1/users?role={role} to fetch users by role
- [ ] Implement server-side logic to handle successful and failed user retrieval requests
- [ ] Implement authentication and authorization checks
- [ ] Ensure all sensitive data is encrypted and secure
- [ ] Implement logging for errors and user retrieval attempts
- [ ] Write unit tests for the fetch users by role endpoint
- [ ] Write integration tests for the fetch users by role logic
- [ ] Perform security testing to ensure data protection and compliance

## Database Schema

```
CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) DEFAULT 'user' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE organizations (
    id VARCHAR(255) PRIMARY KEY,
    company_name VARCHAR(255) UNIQUE NOT NULL,
    company_email VARCHAR(255) UNIQUE,
    industry VARCHAR(255),
    organization_type VARCHAR(255),
    country VARCHAR(255),
    state VARCHAR(255),
    address VARCHAR(255),
    lga VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

```

### Success Response
 - #### Code: 200 OK
 - #### Content:

```
{
    "status_code": 200,
    "success": true,
    "message": "Users retrieved successfully",
    "data": [
        {
            "password": "$2b$12$scVd8tEVQrcE0erdt6Cb.ennIb4snHehWLiD9zi/8c.6IdLcclhmK",
            "is_deleted": false,
            "first_name": "Demo",
            "created_at": "2024-08-06T09:48:50.823323+01:00",
            "is_verified": false,
            "updated_at": "2024-08-06T09:48:50.823323+01:00",
            "last_name": "Guy",
            "id": "066b1e37-31ef-732f-8000-04ec9c35800c",
            "avatar_url": null,
            "email": "user@demo.com",
            "is_active": true,
            "is_super_admin": false
        }
    ]
}
```

### Error Responses
- #### Code: 400 BAD REQUEST
- #### Content:

```
{
  "error": "Invalid product ID"
}
```

- #### Code: 404 NOT FOUND
- #### Content:

```
{
    "success": false,
    "status_code": 404,
    "message": "No users found for this role"
}
```

- #### Code 422: UNPROCESSABLE CONTENT / VALIDATION ERROR
#### Content:

```
{
    "status": false,
    "status_code": 422,
    "message": "Invalid input",
    "errors": [
        {
            "loc": [
                "path",
                "role_id"
            ],
            "msg": "Input should be 'admin', 'user', 'guest' or 'owner'",
            "type": "literal_error"
        }
    ]
}
```

- #### Code: 500 INTERNAL SERVER ERROR
- #### Content:

```
{
  "error": "An unexpected error occurred"
}
```

### Fetch Users by Owner Role
`curl -X GET "https:/<base-url>/api/v1/users/owner/roles`
