### ISSUE TITLE
[FEAT]: Api Endpoint To Get Team Member By ID (SuperAdmin)

### ISSUE THREAD

**Issue by chukssomzzy** [hngprojects/hng_boilerplate_python_fastapi_web#721]
## Description 
API endpoint to get team members by id (superadmin)

## Acceptance Criteria 
- [ ] Only authenticated user who are super admins can access this endpoint 
- [ ] This endpoint should be accessible at `api/v1/team/members/{member_id}`
- [ ] This endpoint should accept **HTTP GET** requests 
- [ ] Request to this endpoint should have a valid authentication token in authorization header 
- [ ] Returns appropriate `forbidden` on access by user without `superadmin` role 
- [ ] Return appropriate status code and response body

## Purpose 
This endpoint serves the role for internal team management within the boilerplate application by `superadmin` enable tracking of team member and get there roles within the company 

## Requirements 
1. **Data Validation** :  The endpoint should validate the request parmeter `member_id` and confirm that the role is present in users table 
2. **Authorization**: The endpoint should confirm that the user is a `superadmin` before allowing access 
3. **Testing**: The endpoint should be tested with unittest 
4. **Integration Test**: The endpoint should be tested with postman 

## Endpoint 
**HTTP [GET]** `/api/v1/team/members/{member_id}`

## API Request Example 

`GET /api/v1/team/members/{member_id}` 
```json
{
    "status_code": 200, 
    "success": true, 
    "message": "Team member fetched successfully", 
    "data": {
        "picture_url": "https://example.com/image.url", 
        "name": "John Doe", 
        "role": "Software Engineer", 
        "facebook_link": null, 
        "xtwitter_link": null, 
    }
}
```
### Bad request
```json 
{
  "message": "string",
  "error": "string",
  "status_code": 400
}
```
### Unauthorized
```json 
{
  "message": "string",
  "error": "string",
  "status_code": 401
}
```
### Not Found
```json 
{
  "message": "string",
  "error": "string",
  "status_code": 404
}
```
### Server Error
```json 
{
  "message": "string",
  "error": "string",
  "status_code": 500
}
```

## Tasks 
- [ ] Develop server side logic to allow get of team members by `member_id` 

## Testing 
- [ ] Implement unit test with pytest
- [ ] Test various scenario to capture every possibility like, Not Authorized User access, Invalid `member_id`, etc
