### ISSUE TITLE
[FEAT]: Endpoint To Remove User From Role

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#743]
## Description:
Implement an endpoint for admin to remove a user from a particular role.
***

## Acceptance Criteria:

-   It should be a `PROTECTED` endpoint, requiring authentication, with access limited to `admins`.
-   It should be a `PUT` request at `/organizations/{org_id}/users/{user_id}/roles/{role_id}`.
-   It should perform that task of removing a user from a role in a seemless manner
***

## Purpose
To enable admins remove and correct user permissions within the system.

## Requirements

- [ ] Develop server-side logic to remove a user from a particular role following _acceptance criteria_ above
- [ ] Test the endpoint for correctness and accuracy.

## Expected Outcome:
The role identified by `role_id` is removed from the user identified by `user_id`.
The system updates the user's role assignments and reflects this change in the database.
***

## Tasks:
 
- [ ]  Create endpoint (`PUT: /organizations/{org_id}/users/{user_id}/roles/{role_id}`) to handle role removal.
- [ ]  Validate `org_id`, `user_id`, and `role_id` provided on the server side, and fetch the objects with the IDs
- [ ]  Confirm that the user with the user_id is a member of the organization and already in the role with the role_id passed.
- [ ]  Fetch and remove the relationship row linking the user to the role from the database
- [ ]  Return self explanatory _success response_ if request goes well, or _failure response_, if it doesn't.
- [ ]  Write comprehensive unit tests for the endpoint.

**Example Request [With Auth Token]:**
```
curl -X POST {rootdomain}/organizations/{org_id}/users/{user_id}/roles/{role_id} \
     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
     -d ....
```

**Response Body [Success]:**
```
{
  "status_code": 200,
  "message": "User successfully removed from role"
}
```

**Response Body [Errors]:**

- _Unrecognized user:_ `{ "status_code": 401, "message": "Could not validate credentials." }`
- _None admin:_ `{ "status_code": 403, "message": "Permission denied as user is not of admin role" }`
- _Invalid role ID:_ `{ "status_code": 404, "message": "Role does not exist" }`
- _User not in role:_ `{ "status_code": 403, "message": "User not found in role" }`
***

## Testing:

- [ ]  Write end-to-end backend unit tests for the operation
- [ ]  Test all possible outcomes (e.g., successful, failed, etc).
