### ISSUE TITLE
[FEAT]: Delete A Single User In A Team

### ISSUE THREAD

**Issue by chukssomzzy** [hngprojects/hng_boilerplate_python_fastapi_web#744]
## Description 
API endpoint to delete team members by id (superadmin)

## Acceptance Criteria 
- [ ] Only authenticated user who are super admins can access this endpoint 
- [ ] This endpoint should be accessible at `api/v1/team/members/{member_id}`
- [ ] This endpoint should accept **HTTP DELETE** requests 
- [ ] Request to this endpoint should have a valid authentication token in authorization header 
- [ ] Returns appropriate `forbidden` on access by user without `superadmin` role 
- [ ] Return appropriate status code and response body

## Purpose 
This endpoint serves the role for internal team management within the boilerplate application by `superadmin` enable tracking of team member and deleting there roles within the company 

## Requirements 
1. **Data Validation** :  The endpoint should validate the request parameter `member_id` and confirm that the role is present in users table 
2. **Authorization**: The endpoint should confirm that the user is a `superadmin` before allowing access 
3. **Testing**: The endpoint should be tested with unittest 
4. **Integration Test**: The endpoint should be tested with postman 

## Endpoint 
**HTTP [DELETE]** `/api/v1/team/members/{member_id}`

## API Request Example 

`DELETE /api/v1/team/members/{member_id}`

### Response 
```json
{
    "status_code": 200, 
    "success": true, 
    "message": "Team member deleted successfully", 
}
```
### Bad request
```json 
{
  "message": "string",
  "error": "string",
  "status_code": 400
}
```
### Unauthorized
```json 
{
  "message": "string",
  "error": "string",
  "status_code": 401
}
```
### Not Found
```json
{
  "message": "string",
  "error": "string",
  "status_code": 404
}
```
### Server Error
```json 
{
  "message": "string",
  "error": "string",
  "status_code": 500
}
```

## Tasks 
- [ ] Develop server side logic to allow deleting of team members by `member_id` 

## Testing 
- [ ] Implement unit test with pytest
- [ ] Test various scenario to capture every possibility like, Not Authorized User access, Invalid `member_id`, etc
