### ISSUE TITLE
[FEAT]: Send Subscription Cancellation Confirmation - Backend 

### ISSUE THREAD

**Issue by Ayobamidele** [hngprojects/hng_boilerplate_python_fastapi_web#75]
### Description
<hr>
Implement a feature to send Subscription Cancellation Confirmation to users. This endpoint should immediately update users about the Subscription Cancellation Confirmation details in the system. Upon being successfully sent, it will return the message confirming it is being delivered with a '200' status. If an error occurs, an appropriate error status will be returned.

### Acceptance Criteria
<hr>

- Subscription must already be canceled

 
### Purpose
<hr>
Users get a record/notification of their subscription cancellation confirmation

### Requirements
<hr>

- [ ] Subscription exists and has been canceled.
- [ ] Ensure only authorized users have access to the endpoint.

## Endpoints
     [POST] /api/v1/user/subscription/notification/cancellation/{id}

**Requests**
```
POST /api/v1/user/subscription/notification/cancellation/{id}
Content-Type: application/json
Authorization: Bearer <access_token>

{
    "id": 1
}

```

**Successful Response**

- Status code: 200

```json
     {
           "message": "Sent Subscription Cancellation Confirmation notification successfully",
           "name": "str",
           "subscription": {
               "id": "int",
               "plan": "str",
               "cancellation_date": "str"
           }
       }
```

**Error Response**

401 **Unauthorized**
```
{
  "status":  "Unauthorized",
  "message":  "Unauthorized. Please log in."
  “status-code”: 401
}
```

400 **Bad Request**
```
{
  "status":  "Bad Request",
  "message":  "Please check the submitted data"
  “status-code”: 400
}
```
404 **No subscription matches id.**
```
{
  "success": false,
  "message": "No Subscription Found",
  "status_code": 404
}
```
500 **Internal Server Error**

```
{
  "success": false,
  "message": "string",
  "status_code": 500
}
```

**Tasks**:
 

- [ ] Create the endpoint: `[POST] /api/v1/user/subscription/notification/cancellation/{id}`
- [ ] Implement the server-side logic to handle subscription cancellations. This includes sending the confirmation notification.
- [ ]  Set up logging to capture errors and notification attempts.
- [ ]  Write unit tests to verify that the cancellation confirmation is sent correctly.

**Testing**:
   - [ ] unit tests, cover scenarios such as valid subscription IDs, invalid subscription IDs, and edge cases.
   - [ ] For security testing, consider aspects like input validation and authorized users.

**Comment by Ayobamidele** [comment]
@Laban254 please could you assign the task back to me, I made a mistake.
