### ISSUE TITLE
[FEAT]: Remove Member From Organization #61

### ISSUE THREAD

**Issue by desgee** [hngprojects/hng_boilerplate_python_fastapi_web#77]
### Issue: Implement API To Remove Members from Organization 

**Acceptance Criteria:**

- Authentication
    -  Only users with admin or superadmin permissions can remove members.
-   Error Handling:
    -   Log errors for invalid requests.

-   Security Measures:
    -   Use HTTPS for secure data transmission.

**Purpose:** To develop an API remove members from an organization

**Requirements:**

-   Develop server-side logic to remove members from an organization.
-   Securely store user status details in the database.
-   Ensure compliance with security standards for handling user information.

**Expected Outcome:**

-   The backend should remove members securely and efficiently.
-   The system should log errors and handle invalid requests appropriately.

**Endpoints:**

**Remove User:**

-   **Description:** An API to Remove User from an organization.
-   **Endpoint:** `/api/v1/organizations/{org_id}/users/{user_id}`
-   **Method:** DELETE
-   **Request Body:**
       No request body needed for this endpoint.
-   **Response (Success):**
   
  ```
{
  "message": "user deleted successfully",
  "status_code": 200
}
```
    
-   **Response (Error):**
    
  ```     
{
  "message": "user not found",
  "error": "404"
}
```

**Tasks:**

- [ ]  Create an endpoint `api/v1/organizations/{org_id}/users/{user_id}` to remove a user from an organization.
- [ ] Implement server-side logic to handle successful and failed remove user requests.
- [ ] Ensure all sensitive data is encrypted and secure.
- [ ] Implement logging for errors and remove user attempts.
- [ ] Write unit tests for the remove user endpoint.
- [ ] Write integration tests for the  remove user logic.
- [ ] Perform security testing to ensure data protection and compliance.

**Testing:**

-   Write unit tests for backend validation and remove user handling.
-   Write integration tests for the end-to-end remove user process.
-   Perform security testing to ensure data protection and compliance.
-   Test various scenarios for remove user.
