### ISSUE TITLE
[FEAT]: Invitation API - Delete Valid Invite (Superadmin)

### ISSUE THREAD

**Issue by Arnthorny** [hngprojects/hng_boilerplate_python_fastapi_web#779]
## Description
Create an API endpoint to handle the deletion of an invitation. 

This API endpoint will be available at `/api/v1/invite/:invite_id`. It will also validate the `invite_id` parameter. 

## Acceptance Criteria
* The endpoint  allows only authenticated users with superadmin permisssions to delete invites.
* Returns a `200` status code and the correct response body when invite is successfully deleted.
* Returns a `404` status code when an invalid invite_id is passed in as path parameter.
* Returns a `401` status code when the user is not authenticated.
* Returns a `403` status code when the user is not authorized.
* Returns a `500` status code when a server error occurs.

### Requirements
* Implement API endpoint for deleting invitations.
* The endpoint should validate the path parameter to ensure that the invite_id parameter is present and valid.
* Ensure response is properly structured.
* Handle unexpected errors and return the appropriate status code.

### Expected Outcome
Successful deletion of invitation with given `invite_id`.

### Endpoint:
HTTP [DELETE] **/api/v1/invite/:invite_id**

* **Description**: Delete invitation.

### Responses
* **Success Response**:
  
  * Status: `200 OK`
  * Body:

```json
{
  "success": true,
  "message": "Invite deleted successfully",
  "status_code": 200,
}
```

* **Unauthorized Response**:
  
  * Status: `401 Unauthenticated`
  * Body:

```json
{
  "success": false,
  "message": "Not authenticated",
  "status_code": 401
}
```

* **Invalid ID**:
  
  * Status: `404 Not Found`
  * Body:

```json
{
  "message": "Invalid invitation id",
  "status_code": 404,
  "success": false
}
```

* **Server Error Response**:
  
  * Status: `500 Server Error`
  * Body:

```json
{
  "success": false,
  "message": "<string>",
  "status_code": 500
}
```

## Tasks
* [x]  Develop server-side logic to handle invite deletion requests.
* [x]  Validate incoming invite ID parameter.
* [x]  Confirm that the user deleting the invite is an admin.

## Test Scenarios

1. **Successful Deletion of Invitations**
   
   * Ensure that the endpoint successfully deletes invite from the database.
   * Confirm that the status code is `200 OK`.
   * Verify that the response body contains the expected data.

2. **Unauthenticated Request**
   
   * Send a request without being authenticated.
   * Verify that the endpoint returns a `401 Unauthenticated` status code.

3. **Unauthorized Request**
   
   * Send a request without being authorized.
   * Verify that the endpoint returns a `403 Forbidden` status code.

**Comment by joboy-dev** [comment]
This has been implemented
