### ISSUE TITLE
[FEAT] Get Single Billing Plan

### ISSUE THREAD

**Issue by JoshuaOloton** [hngprojects/hng_boilerplate_python_fastapi_web#827]
# Get Single Billing Plan API Endpoint

## Description

Develop an API endpoint that retrieves the details of a single billing plan. The endpoint should accept a `billing_plan_id` and return the corresponding billing plan's details.

## Acceptance Criteria

- The endpoint `/api/v1/organizations/billing-plans/{billing_plan_id}` is accessible via a GET request.
- When a valid `billing_plan_id` is provided, the endpoint returns a 200 OK status with the billing plan details.
- When an invalid `billing_plan_id` is provided, the endpoint returns a 400 Bad Request status.
- If the billing plan is not found, the endpoint returns a 404 Not Found status.
- If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status.
- The response body of an error 500 response contains an error message indicating that an unexpected error occurred.
- Ensure that all unit and integration tests for the get single billing plan endpoint are comprehensive and verify the functionality correctly.

### Purpose

- This provides a backend service that allows retrieving details of a specific billing plan.

### Requirements

- [ ] Implement an endpoint to get the details of a single billing plan.

### Expected Outcome

- API endpoint that securely retrieves and returns the details of a billing plan.

### Tasks

- [ ] Create an endpoint `/api/v1/organizations/billing-plans/{billing_plan_id}` to retrieve the billing plan details.
- [ ] Implement authorization to ensure only authorized users can retrieve billing plan details.
- [ ] Implement logging for billing plan retrieval attempts and errors.
- [ ] Write unit tests for the get single billing plan endpoint.

## Database Schema
```sql
Table billing_plans {
  id int [pk, increment] // Primary key
  name varchar [not null]
  price decimal [not null]
  duration int [not null] // Duration in days
  features jsonb
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp
}
```

## Authorization
- Bearer Token (JWT) required in the Authorization header
- Format: Authorization: Bearer <your_jwt_token>

### Success Response
 - #### Code: 200 SUCCESS
 - #### Content:
```json
{
    "message": "Billing plan retrieved successfully",
    "success": true,
    "status": 200,
    "billing_plan": {
        "id": 1,
        "name": "Basic Plan",
        "price": 29.99,
        "duration": 30,
        "features": {
            "feature_1": "Feature description",
            "feature_2": "Feature description"
        }
    }
}

```

### Error Responses
 - #### Code: 400 BAD REQUEST
 - #### Content:
 ```
{
 "error": "Invalid billing plan ID"
}

 ```
 
 - #### Code: 422: UNPROCESSABLE CONTENT / VALIDATION ERROR
 - #### Content:
 ```
 {
  "errors": {
    "field": "<field>",
    "message": "<message>"
  }
}
```

 - #### Code: 404 NOT FOUND
 - #### Content:
 ```
{
 "error": "Billing plan not found"
}

```

 - #### Code: 500 INTERNAL SERVER ERROR
 - #### Content:
 ```
{
  "error": "An unexpected error occurred"
}
```

### Get Single Billing Plan

```
curl -X GET "https://<base-url>/api/v1/organizations/billing-plans/456" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer <your_jwt_token>"
```
