### ISSUE TITLE
[FEAT]: Retrieve Product Details

### ISSUE THREAD

**Issue by theijhay** [hngprojects/hng_boilerplate_python_fastapi_web#83]
**Description:**

Develop a backend API endpoint to allow logged-in users to retrieve the details of a specific product. This functionality is part of the product management system and requires user authentication.

**Acceptance Criteria:**

**Endpoint security:**

Only authenticated users can have access to the endpoint
A user must have the appropriate permissions to access the endpoint
Each request to the endpoint must include a valid authentication token in the

**1. Retrieve Product Details:**
- **Method:** GET
- **URL:** `/api/v1/products/:id`
- **Request:**
  - **Headers:**
    - `Authorization: Bearer <JWT_token>`
- **Response:**
  **On successful retrieval:**
  ```json
  {
    "status": "success",
    "message": "Product details retrieved successfully",
    "status_code": 200,
    "data": {
      "id": 1,
      "name": "string",
      "price": 45.0
      "description": "string",
    }
  }
  ```
  **On error (e.g., product not found):**
  ```json
  {
    "status": "error",
    "message": "Product not found",
    "status_code": 404
  }
  ```
  **On error (e.g., unauthorized access):**
  ```json
  {
    "status": "error",
    "message": "Unauthorized access",
    "status_code": 401
  }
  ```
**Validation:**
- Validate the JWT auth token.
- Validate that the `id` exists and the user is authorized to view the product.

**Purpose:**
To provide a secure and authenticated endpoint for retrieving details of a specific product, ensuring only authorized users can access this information.

**Expected Outcome:**
A fully functional backend API endpoint that allows logged-in users to retrieve product details, with proper validation and error handling.

**Tasks:**
- [ ] Implement the GET endpoint to retrieve product details.
- [ ] Validate inputs and handle errors appropriately.
- [ ] Write unit tests for the endpoint to ensure it handles valid and invalid inputs correctly.

**Test Scenarios:**
1. **Successful product retrieval:** Verify that a logged-in user can retrieve product details with a valid product ID.
2. **Product not found:** Verify that the endpoint returns a 404 status code when the product does not exist.
3. **Unauthorized access:** Verify that the endpoint returns a 401 status code when the user is not authorized to view the product.
4. **Validation error:** Verify that the endpoint returns a 400 status code when required parameters are missing or incorrectly formatted.

**Comment by theijhay** [comment]
This is the [link](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/152) to the approval ticket.

**Comment by theijhay** [comment]
@Laban254   You did not assign me

**Comment by Laban254** [comment]
Done

**Comment by JoshuaOloton** [comment]
This is a duplicate of #62

**Comment by theijhay** [comment]
Don't forget that @zxenonx has checked this already. you can contact him @JoshuaOloton
