### ISSUE TITLE
[FEAT]: Endpoint To Delete Blog Like

### ISSUE THREAD

**Issue by traderstechie** [hngprojects/hng_boilerplate_python_fastapi_web#965]
### Description:
Implement an endpoint to enable users and readers who liked a blog post to remove same.

## Acceptance Criteria:

-   It should be a `PROTECTED` endpoint, requiring authentication.
-   It should be a `POST` request at `/api/v1/blogs/likes/:{blog_like_id}`.
-   It should remove **BlogLike** from the database and return appropriate message to the user.
-   It should allow ONLY the user who posted the like to delete it.
***

## Purpose
To enable a blog post readers to remove like from any particular post after adding one.

## Requirements

- [ ] Develop server-side logic to delete **like** from a blog post following _acceptance criteria_ above
- [ ] Test the endpoint for correctness and accuracy.

## Expected Outcome:
Blog readers should be able to remove like from a blog post if they posted it in error or just changed their mind.
***

## Tasks:
 
- [ ]  Create endpoint (`POST: /api/v1/blogs/likes/:{blog_like_id}`) to handle request.
- [ ]  Validate `blog_like_id`, access `BlogLike` object and confirm that requester created it.
- [ ]  Delete the `BlogLike` object from the database
- [ ]  Return self explanatory _success response_ if request goes well, or _failure response_, if it doesn't.
- [ ]  Write comprehensive unit tests for the endpoint and operation.

**Example Request [With Auth Token]:**
```
curl -X POST {rootdomain}/api/v1/blogs/likes/:{blog_like_id} \
     -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
     -d ....
```

**Response Body [Success]:**
```
status_code: 204
```

**Response Body [Errors]:**

- _Unrecognized user:_ `{ "status_code": 401, "message": "Could not validate credentials." }`
- _Not the blog like owner:_ `{ "status_code": 401, "message": "Insufficient permission" }`
- _Invalid blog ID:_ `{ "status_code": 404, "message": "BlogLike does not exist." }`***

## Testing:

- [ ]  Write end-to-end backend unit tests for the delete blog like process.
- [ ]  Test all possible outcomes and reactions for like (e.g., successful, failed, etc).
***

## Added Fix:
Enable `/api/v1/blogs/{blog_id}/like`  to delete existing `dislike` by the `current_user` before creating new `like`, and vice versa with the `/api/v1/blogs/{blog_id}/dislike` endpoint.

**Comment by simplicityf** [comment]
I will like to be assigned this issue please

**Comment by Takinnuoye5** [comment]
approved

**Comment by chimeziriobioha** [comment]
Hey @Takinnuoye5 this was already done and merged in HNG11. Same with most of the issues that dates back to August 2024 and earlier. They were not just closed. You can see a merged PR mentioned after the issue details. I got a mail as you commented on it now, because I created the issue then. Just thought I should mention it.✌️

**Comment by simplicityf** [comment]
Looking at the routes method, it was not well defined, there was no proper
error handling also as stated in the issue Description.

I don't think so

**Comment by chimeziriobioha** [comment]
Alright, if something is not right with the current implementation, the better way forward would be to create a new issue that captures the problem and improvement to be made. Except new issues are not allowed. I'm not part of the current program, though. Just an alumni who happened to be part of this project.
